package net.jeeshop.core.model;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.account
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.nickname
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.password
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.city
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.address
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.postcode
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.cardType
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.cardNO
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.grade
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.amount
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.tel
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.email
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.emailIsActive
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String emailisactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.freeze
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String freeze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.lastLoginTime
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.lastLoginIp
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String lastloginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.lastLoginArea
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String lastloginarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.diffAreaLogin
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String diffarealogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.regeistDate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Date regeistdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.freezeStartdate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Date freezestartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.freezeEnddate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Date freezeenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.openId
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.accessToken
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String accesstoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.alipayUseId
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String alipayuseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.sinaWeiboID
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String sinaweiboid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.sex
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.trueName
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.birthday
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.province
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.accountType
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.rank
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.score
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    private Integer score;
    
    /**
     * This field was generated by cdx.
     * This field corresponds to the database column t_account.casOpenID
     *
     * @author cdx 2015-8-3
     */
    private String casOpenID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.account
     *
     * @return the value of t_account.account
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.account
     *
     * @param account the value for t_account.account
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.nickname
     *
     * @return the value of t_account.nickname
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.nickname
     *
     * @param nickname the value for t_account.nickname
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.password
     *
     * @return the value of t_account.password
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.password
     *
     * @param password the value for t_account.password
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.city
     *
     * @return the value of t_account.city
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.city
     *
     * @param city the value for t_account.city
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.address
     *
     * @return the value of t_account.address
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.address
     *
     * @param address the value for t_account.address
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.postcode
     *
     * @return the value of t_account.postcode
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.postcode
     *
     * @param postcode the value for t_account.postcode
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.cardType
     *
     * @return the value of t_account.cardType
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.cardType
     *
     * @param cardtype the value for t_account.cardType
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.cardNO
     *
     * @return the value of t_account.cardNO
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.cardNO
     *
     * @param cardno the value for t_account.cardNO
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.grade
     *
     * @return the value of t_account.grade
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.grade
     *
     * @param grade the value for t_account.grade
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.amount
     *
     * @return the value of t_account.amount
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.amount
     *
     * @param amount the value for t_account.amount
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.tel
     *
     * @return the value of t_account.tel
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.tel
     *
     * @param tel the value for t_account.tel
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.email
     *
     * @return the value of t_account.email
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.email
     *
     * @param email the value for t_account.email
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.emailIsActive
     *
     * @return the value of t_account.emailIsActive
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getEmailisactive() {
        return emailisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.emailIsActive
     *
     * @param emailisactive the value for t_account.emailIsActive
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setEmailisactive(String emailisactive) {
        this.emailisactive = emailisactive == null ? null : emailisactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.freeze
     *
     * @return the value of t_account.freeze
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getFreeze() {
        return freeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.freeze
     *
     * @param freeze the value for t_account.freeze
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setFreeze(String freeze) {
        this.freeze = freeze == null ? null : freeze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.lastLoginTime
     *
     * @return the value of t_account.lastLoginTime
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.lastLoginTime
     *
     * @param lastlogintime the value for t_account.lastLoginTime
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.lastLoginIp
     *
     * @return the value of t_account.lastLoginIp
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.lastLoginIp
     *
     * @param lastloginip the value for t_account.lastLoginIp
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip == null ? null : lastloginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.lastLoginArea
     *
     * @return the value of t_account.lastLoginArea
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getLastloginarea() {
        return lastloginarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.lastLoginArea
     *
     * @param lastloginarea the value for t_account.lastLoginArea
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setLastloginarea(String lastloginarea) {
        this.lastloginarea = lastloginarea == null ? null : lastloginarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.diffAreaLogin
     *
     * @return the value of t_account.diffAreaLogin
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getDiffarealogin() {
        return diffarealogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.diffAreaLogin
     *
     * @param diffarealogin the value for t_account.diffAreaLogin
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setDiffarealogin(String diffarealogin) {
        this.diffarealogin = diffarealogin == null ? null : diffarealogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.regeistDate
     *
     * @return the value of t_account.regeistDate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Date getRegeistdate() {
        return regeistdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.regeistDate
     *
     * @param regeistdate the value for t_account.regeistDate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setRegeistdate(Date regeistdate) {
        this.regeistdate = regeistdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.freezeStartdate
     *
     * @return the value of t_account.freezeStartdate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Date getFreezestartdate() {
        return freezestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.freezeStartdate
     *
     * @param freezestartdate the value for t_account.freezeStartdate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setFreezestartdate(Date freezestartdate) {
        this.freezestartdate = freezestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.freezeEnddate
     *
     * @return the value of t_account.freezeEnddate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Date getFreezeenddate() {
        return freezeenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.freezeEnddate
     *
     * @param freezeenddate the value for t_account.freezeEnddate
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setFreezeenddate(Date freezeenddate) {
        this.freezeenddate = freezeenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.openId
     *
     * @return the value of t_account.openId
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.openId
     *
     * @param openid the value for t_account.openId
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.accessToken
     *
     * @return the value of t_account.accessToken
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.accessToken
     *
     * @param accesstoken the value for t_account.accessToken
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken == null ? null : accesstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.alipayUseId
     *
     * @return the value of t_account.alipayUseId
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getAlipayuseid() {
        return alipayuseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.alipayUseId
     *
     * @param alipayuseid the value for t_account.alipayUseId
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setAlipayuseid(String alipayuseid) {
        this.alipayuseid = alipayuseid == null ? null : alipayuseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.sinaWeiboID
     *
     * @return the value of t_account.sinaWeiboID
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getSinaweiboid() {
        return sinaweiboid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.sinaWeiboID
     *
     * @param sinaweiboid the value for t_account.sinaWeiboID
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setSinaweiboid(String sinaweiboid) {
        this.sinaweiboid = sinaweiboid == null ? null : sinaweiboid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.sex
     *
     * @return the value of t_account.sex
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.sex
     *
     * @param sex the value for t_account.sex
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.trueName
     *
     * @return the value of t_account.trueName
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.trueName
     *
     * @param truename the value for t_account.trueName
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.birthday
     *
     * @return the value of t_account.birthday
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.birthday
     *
     * @param birthday the value for t_account.birthday
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.province
     *
     * @return the value of t_account.province
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.province
     *
     * @param province the value for t_account.province
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.accountType
     *
     * @return the value of t_account.accountType
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.accountType
     *
     * @param accounttype the value for t_account.accountType
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype == null ? null : accounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.rank
     *
     * @return the value of t_account.rank
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.rank
     *
     * @param rank the value for t_account.rank
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.score
     *
     * @return the value of t_account.score
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.score
     *
     * @param score the value for t_account.score
     *
     * @mbggenerated Mon Jun 29 11:29:18 CST 2015
     */
    public void setScore(Integer score) {
        this.score = score;
    }
    
    /**
     * This method was generated by cdx.
     * This method returns the value of the database column t_account.casOpenID
     *
     * @return the value of t_account.casOpenID
     *
     * @author cdx 2015-8-3
     */
	public String getCasOpenID() {
		return casOpenID;
	}
	
	 /**
     * This method was generated by cdx.
     * This method sets the value of the database column t_account.casOpenID
     *
     * @param score the value for t_account.casOpenID
     *
     * @author cdx 2015-8-3
     */
	public void setCasOpenID(String casOpenID) {
		this.casOpenID = casOpenID;
	}
}