package net.jeeshop.core.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import net.jeeshop.core.model.base.BaseModel;
import net.jeeshop.core.util.MathUtil;

public class Cart extends BaseModel implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	private static final long serialVersionUID = 1L;
	
	private BigDecimal amount;
	
	private BigDecimal score;
	
	/**
	 * @Fields items : （购物车明细）
	 */
	private List<CartItem> items;
	
    /**
	 * items getter method
	 * @return the items
	 */
	public List<CartItem> getItems() {
		return items;
	}

	/**
	 * items setter method
	 * @param items the items to set
	 */
	public void setItems(List<CartItem> items) {
		this.items = items;
	}
	
	/**
	 * amount getter method
	 * @return the amount
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * amount setter method
	 * @param amount the amount to set
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	
	public BigDecimal getScore() {
		return score;
	}

	public void setScore(BigDecimal score) {
		this.score = score;
	}

	public Cart calculate(){
		BigDecimal result = new BigDecimal(0);
		BigDecimal score = new BigDecimal(0);
		for (CartItem item : getItems()) {
			result = MathUtil.add(result, item.calculate());
			score = MathUtil.add(score, item.calculateScore());
		}
		setAmount(result);
		setScore(score);
		return this;
	}
}