package net.jeeshop.core.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import net.jeeshop.core.model.base.BaseModel;
import net.jeeshop.core.util.MathUtil;
import net.jeeshop.services.front.product.bean.Product;

public class CartItem extends BaseModel implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart_item.cart_id
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	private String cartId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart_item.sku_id
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	private String skuId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart_item.quantity
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	private Integer quantity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart_item.add_price
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	private BigDecimal addPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart_item.add_time
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_cart_item
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart_item.cart_id
	 * @return  the value of t_cart_item.cart_id
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public String getCartId() {
		return cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart_item.cart_id
	 * @param cartId  the value for t_cart_item.cart_id
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart_item.sku_id
	 * @return  the value of t_cart_item.sku_id
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public String getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart_item.sku_id
	 * @param skuId  the value for t_cart_item.sku_id
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public void setSkuId(String skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart_item.quantity
	 * @return  the value of t_cart_item.quantity
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart_item.quantity
	 * @param quantity  the value for t_cart_item.quantity
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart_item.add_price
	 * @return  the value of t_cart_item.add_price
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public BigDecimal getAddPrice() {
		return addPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart_item.add_price
	 * @param addPrice  the value for t_cart_item.add_price
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public void setAddPrice(BigDecimal addPrice) {
		this.addPrice = addPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart_item.add_time
	 * @return  the value of t_cart_item.add_time
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart_item.add_time
	 * @param addTime  the value for t_cart_item.add_time
	 * @mbggenerated  Wed Aug 05 14:02:10 CST 2015
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * @Fields sku : （购物车明细中的商品）
	 */
	private Product sku;
	
	/**
	 * @Fields amount : （购物车明细金额小计）
	 */
	private BigDecimal amount;
	
	public BigDecimal calculate() {
		setAmount(MathUtil.multiply(new BigDecimal(getSku().getNowPrice()), new BigDecimal(getQuantity())));
		return getAmount();
	}
	
	/**
	 * sku getter method
	 * @return the sku
	 */
	public Product getSku() {
		return sku;
	}

	/**
	 * sku setter method
	 * @param sku the sku to set
	 */
	public void setSku(Product sku) {
		this.sku = sku;
	}

	/**
	 * amount getter method
	 * @return the amount
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * amount setter method
	 * @param amount the amount to set
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	
	private BigDecimal score;

	public BigDecimal getScore() {
		return score;
	}

	public void setScore(BigDecimal score) {
		this.score = score;
	}
	
	public BigDecimal calculateScore() {
		setScore(MathUtil.multiply(new BigDecimal(getSku().getScore()), new BigDecimal(getQuantity())));
		return getScore();
	}
	
}