package net.jeeshop.dao.impl.mybatis.mapper;

import java.util.List;
import net.jeeshop.core.model.Cart;
import net.jeeshop.core.model.CartExample;
import org.apache.ibatis.annotations.Param;

public interface CartMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int countByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int deleteByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int insert(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int insertSelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	List<Cart> selectByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	Cart selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Cart record,
			@Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int updateByExample(@Param("record") Cart record,
			@Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int updateByPrimaryKeySelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cart
	 * @mbggenerated  Tue Aug 04 16:38:02 CST 2015
	 */
	int updateByPrimaryKey(Cart record);
}